version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           apt install default-jre -y
           apt install nano -y
           apt install flex -y
           git clone https://github.com/PETRIK-CROT/android_kernel_realme_sdm710 ~/petrik
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
